# Generated by Django 4.2.16 on 2026-09-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='zip_code',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='review',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='review',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='review',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
